[project]
name = "flask-sync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.0",
    "python-dotenv>=1.0.0",
    "sqlalchemy>=2.0.40",
    "uwsgi>=2.0.28",
]
