[project]
name = "fastapi-async"
version = "0.1.0"
description = "FastAPI async example"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.27.1",
] 