[project]
name = "fastapi-async"
version = "0.1.0"
description = "FastAPI async example"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.110.0",
    "greenlet>=3.1.1",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.27.1",
] 
